# Generated by Django 6.1.1 on 2026-10-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_request_updated_at_alter_request_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='SearchRequest',
        ),
    ]
